### ISSUE TITLE
想提一个功能性建议：根据页面的墨水覆盖率定价

### ISSUE THREAD

**Issue by JackalZhao** [tongxunkeji/printyun#4]
一些场景可能会遇到：
某些客户很喜欢打深色背景的文件；挂上无人自助打印时，可能遭一些人恶意打印，故意打印全黑那种纸张，快速消耗墨水、墨粉。
以上两种情况会导致墨水使用异常的快，平白无故增加成本，如果是贴着成本做打印，可能会做亏。
如果能做分析页面的墨水覆盖率，覆盖率过高时使用特殊的定价策略，就可以解决这个问题。
一个思路是，文件上传后，将打印的每一页都转换成一个低分辨率的缩略图，计算出缩略图的平均亮度B。纯白则是B=255，代表0%覆盖率；纯黑即是B=0，代表100%覆盖率；覆盖率P计算公式粗略为P=1-B/255。
再将每页的覆盖率加合平均一下，算出整个文档文件每页的平均覆盖率。这样就可以分覆盖率计算价格，例如正常文档打印1毛1页；平均覆盖率>20%的时候改为2毛；平均覆盖率>80%的时候，很可能就是捣乱了，计算价格时5毛/页。

（不过可惜我才疏学浅，只能想想这个思路，没能力做出这个功能）

**Comment by tongxunkeji** [comment]
十分感谢建议！如果商业化后确实是个大问题，我们会积极改善！
